#!/usr/bin/env python3

import urllib.request
import subprocess
import os

def mirrorlist():

    pm = "/etc/pacman.d/"
    os.chdir(pm)
    country = "SE"
    num = "3"
    mirrors = urllib.request.urlopen("https://www.archlinux.org/mirrorlist/?country=" + country)
    m_list = mirrors.read()
    with open("tmp_mirrorlist", "wb") as code:
        code.write(m_list)

    subprocess.call(["sed","-i","s/^#Server/Server/","tmp_mirrorlist"], cwd = pm)

    cmd = subprocess.Popen(["rankmirrors","-n",num,"tmp_mirrorlist"], stdout=subprocess.PIPE, cwd = pm)
    out = cmd.stdout.read()
    with open("mirrorlist", "wb") as code:
        code.write(out)

def pacstrap():

    subprocess.call(["pacstrap","/mnt", "base", "base-devel"])

def genfstab():

    cmd = subprocess.Popen(["genfstab","-U","/mnt"], stdout=subprocess.PIPE,])
    out = cmd.stdout.read()
    os.chdir("/mnt/etc/")
    with open("fstab", "wb") as code:
        code.write.(out)

def chroot():
    subprocess.call(["arch-chroot","/mnt","/bin/bash"])
    subprocess.call(["ln","-s","/usr/share/zoneinfo/Europe/Copenhagen", "/etc/localtime"])
    subprocess.call(["hwclock","--systohc","--utc"])

    with open("/etc/locale.gen", "wb") as code:
        code.write("sv_SE.UTF-8 UTF-8")

    subprocess.call(["locale-gen"])

    with open("/etc/vconsole.conf", "wb") as code:
        code.write("sv-latin1")

    hostname = "off-world"
    with open("/etc/hostname", "wb") as code:
        code.write(hostname)

    subprocess.call(["mkinitcpio","-p","linux"])

    subprocess.call(["passwd"])
    subprocess.call(["pacman","-S","grub"])
    subprocess.call(["grub-install","--target=i386-pc","/dev/sda"])
    subprocess.call(["grub-mkconfig","-o","/boot/grub/grub.cfg"])


mirrorlist()     
