#!/usr/bin/env bash
 
  ####  #    # #    #  ####  License: GNU GPLv3
 #    # ##   # #    # #      Year: 2020
 #      # #  # #    #  ####  
 #  ### #  # # #    #      # https://github.com/gnusd
 #    # #   ## #    # #    # http://gnusd.xyz 
  ####  #    #  ####   ####
 
# FILENAME: audiosplit

split () {
	cuebreakpoints *.cue | shnsplit -o flac "$audio_file"
	cuetag *.cue split-track*.flac
	rm "$audio_file"
}

toflac () {
	file="${input// /_}"
	filename="${file%%.*}.flac"
	ffmpeg -i "$input" -c:a flac $filename && rm "$input"
}

for file in *
do
	ext="${file##*.}"
	echo "$ext"
	case "$ext" in
		flac)
			audio_file="$file"
			split
			;;
		ape)
			input="$file"
			toflac
			audio_file="$filename"
			split
			;;
		wv)
			input="$file"
			toflac
			audio_file="$filename"
			split
			;;
		*)
	esac
done
