#!/usr/bin/env bash

 ####  #    # #    #  ####  License: GNU GPLv3
#    # ##   # #    # #      Year: 2020
#      # #  # #    #  ####
#  ### #  # # #    #      # https://github.com/gnusd
#    # #   ## #    # #    # http://gnusd.xyz
 ####  #    #  ####   ####

## FILENAME: audio

check_audio () {
		non_flac_files=0
		flac_file=0
		# count number of audiofiles in directory
		for aufile in *
		do
				ext="${aufile##*.}"
				if [ "$ext" == "flac" ]
				then
						let "flac_file++"
						AUDIO_FILE="$aufile"
				elif [[ "$ext" == "m4a" || "$ext" == "ape" || "$ext" == "wav" || "$ext" == "wv" ]]
				then
						let "non_flac_files++"
						AUDIO_FILE="$aufile"
				fi
		done
		let "num_audio_files=$non_flac_files + $flac_file"

		if [ "$num_audio_files" -gt 1 ]
		then
				if [ "$non_flac_files" -gt 1 ]
				then
						for file in *
						do
								ext="${file##*.}"
								case "$ext" in
										ape | wv | m4a | wav)
												input="$file"
												toflac
												;;
										*)
								esac
						done
						exit
				fi
				unset_local_varibles
		else
				if [ "$non_flac_files" == 1 ]
				then
						toflac
						process_signle_audiofile
				else
						process_signle_audiofile
				fi
		fi
}

get_extension () {
		tmp="${1##*.}"
}

get_file_name () {
		tmp="${1%%.*}"
}

delete () {
		printf '%s' "Delete flac & cue file [Y/n] "
		read -r response

		if [ "$response" != "${response#[Nn]}" ]
				then
						mv "$AUDIO_FILE" "$AUDIO_FILE".bak
				else
						rm "$AUDIO_FILE" "$CUE_FILE"
						fi
}

rename () {
		tmp=$"(echo "$1" | sed 's/[^0-9a-zA-Z.]/_/g')"
}

unset_local_varibles () {
		unset CUE_FILE
		unset AUDIO_FILE
}

recursiverm() {
		for d in *
		do
			if [ -d "$d" ]
			then
				(cd -- "$d" && recursiverm)
			fi
		done
}
main () {
		for file in *
		do
			ext="${file##*.}"
			if [[  "$ext" == "flac" || "$ext" == "m4a" || "$ext" == "ape" || "$ext" == "wav" || "$ext" == "wv" ]]
			then
				export AUDIO_FILE="$file"
				check_cue
				check_audio
				split
				delete
				unset_local_varibles
			fi
		done
}
