#!/usr/bin/env bash

  ####   #    # #    #  ####  License: GNU GPLv3
  #    # ##   # #    # #      Year: 2020
  #      # #  # #    #  ####
  #  ### #  # # #    #      # https://github.com/gnusd
  #    # #   ## #    # #    # http://gnusd.xyz
  ####   #    #  ####   ####

# FILENAME: audiosplit

split () {
		cue_file="$(ls | grep \.cue$)"
		cuebreakpoints "$cue_file" | shnsplit -o flac "$audio_file"
		cuetag "$cue_file" split-track*.flac
}

check_cue () {
		name_cue_file="$(ls | grep \.cue$)"

		file_name="${name_cue_file%%.*}"
		cue_name="$(echo $file_name | sed 's/[^0-9a-zA-Z]//g').cue"
		if [ "$name_cue_file" != "$cue_name" ]
		then
				mv "$name_cue_file" "$cue_name"
				name_cue_file="$cue_name"
		fi
		num_tracks="$(cat "$name_cue_file" | grep -c TRACK)"
		if [ "$num_tracks" -lt 1 ]
		then
				echo "Probably not a cue file"
		elif [ "num_tracks" == 1 ]
		then
				echo "Check cue sheet, possible only one track."
		fi
}

check() {
		check_cue

		file_name="${audio_file%%.*}"
		audio_name="$(echo $file_name | sed 's/[^0-9a-zA-Z]//g').flac"
		if [ "$audio_file" != "$audio_name" ]
		then
				mv "$audio_file" "$audio_name"
				audio_file="$audio_name"
		fi
		bitrate=$(mediainfo "$audio_file" | grep "depth" | sed 's/[^0-9]*//g')

		if [ "$bitrate" -gt 16 ]
		then
				tmp_file="${audio_file%%.*}tmp.flac"
				cp "$audio_file" "$tmp_file" && rm "$audio_file"
				ffmpeg -i "$tmp_file" -af aformat=s16:44100 "$audio_file" && rm "$tmp_file"
		fi
}

delete () {
		printf '%s' "Delete flac & cue file [y/N] "
		read -r response

		if [ "$response" != "${response#[Yy]}" ]
		then
				rm "$audio_file" *.cue
		else
				mv "$audio_file" "$audio_file".bak
		fi
}

beets () {
		printf '%s' "Import to beets  [y/N] "
		read -r response

		if [ "$response" != "${response#[Yy]}" ]
		then
				beet import .
		fi
}

toflac () {
		file="${input// /_}"
		filename="${file%%.*}.flac"
		ffmpeg -i "$input" -c:a flac $filename && rm "$input"
}

for file in *
do

		ext="${file##*.}"
		case "$ext" in
				flac)
						audio_file="$file"
						check
						split
						delete
						beets
						;;
				ape | wv | m4a)
						input="$file"
						toflac
						audio_file="$filename"
						check
						split
						delete
						beets
						;;
				*)
		esac
done
