#!/usr/bin/env bash

 #####  #    # #    #  ####  License: GNU GPLv3
 #    # ##   # #    # #      Year: 2021
 #      # #  # #    #  ####
 #  ### #  # # #    #      # https://github.com/gnusd
 #    # #   ## #    # #    # http://gnusd.xyz
 #####  #    #  ####   ####

# FILENAME: beet

FLAG="$1"

HELP () {

	echo -e "\n \n\t Usage: beet OPTION \n\t ------------------ \n\t -i --import  \t to import to database \n\t -u --update  \t to update database"
	exit
}


[ -z "$FLAG" ] && HELP

delete () {
	printf '%s' "Clear import directory [Y/n] "
	read -r response

	if [ "$response" != "${response#[Nn]}" ]
	then
		rm -rf "$HOME/mnt/downloads/imports/*"
	fi
}

progressbar () {
		echo -ne 'initializing [                ]\r'
		sleep 1
		echo -ne 'initializing [#               ]\r'
		sleep 1
		echo -ne 'initializing [##              ]\r'
		sleep 1
		echo -ne 'initializing [###             ]\r'
		sleep 1
		echo -ne 'initializing [####            ]\r'
		sleep 1
		echo -ne 'initializing [#####           ]\r'
		sleep 1
		echo -ne 'initializing [######          ]\r'
		sleep 1
		echo -ne 'initializing [#######         ]\r'
		sleep 1
		echo -ne 'initializing [########        ]\r'
		sleep 1
		echo -ne 'initializing [#########       ]\r'
		sleep 1
		echo -ne 'initializing [##########      ]\r'
		sleep 1
		echo -ne 'initializing [###########     ]\r'
		sleep 1
		echo -ne 'initializing [############    ]\r'
		sleep 1
		echo -ne 'initializing [#############   ]\r'
		sleep 1
		echo -ne 'initializing [##############  ]\r'
		sleep 1
		echo -ne 'initializing [############### ]\r'
		sleep 1
		echo -ne 'initializing [################]\r'
		sleep 1
		echo -ne '\n'
}

if [[ "$FLAG" == "--import" || "$FLAG" == "-i" ]]
then
	cd $HOME/docker/beets
	docker-compose up -d
	    progressbar
	    docker exec -u abc -it beets /bin/bash -c 'beet import /downloads'
	docker-compose down
	    delete

elif [[ "$FLAG" == "--update" || "$FLAG" == "-u" ]]
then
	cd $HOME/docker/beets
	docker-compose up -d
	    progressbar
	    docker exec -it beets /bin/bash -c 'beet update'
	docker-compose down

elif [[ "$FLAG" == "--art" || "$FLAG" == "-a" ]]
then
	cd $HOME/docker/beets
	docker-compose up -d
	    progressbar
	    docker exec -it beets /bin/bash -c 'beet fetchart'
	docker-compose down
else
	HELP
fi
