#!/bin/sh
#
# 	  mmmm  m mm   m   m   mmm
# 	 #" "#  #"  #  #   #  #   "
# 	 #   #  #   #  #   #   """m
# 	 "#m"#  #   #  "mm"#  "mmm"
#  	  m  #
#      ""
# a scrip parsing dotfiles for aliases and key bindings

# GLOBAL VARIABLES
DOTFILE_DIR="$HOME/repositories/dotfiles"
CONFIG_DIR="$HOME/repositories/dotfiles/.config"
CHOISE="zshalias ssh nvim help"
PATERN="##"
INPUT=""

# Checking if $1 is in CHOISE
result=$(echo "$CHOISE" | grep "$1")

# Checking which query to run
[ -z "$result" ] && INPUT="$1" && unset "$1" && filename="$CONFIG_DIR/zsh/alias.zsh"
[ "$1" = "zshalias" ] || [ -z "$1" ] && filename="$CONFIG_DIR/zsh/alias.zsh"
[ "$1" = "ssh" ] && filename="$DOTFILE_DIR/.ssh/ssh_alias" && [ ! -z "$2" ] && grp="ssh" && INPUT="$2"
[ "$1" = "nvim" ] && filename="$CONFIG_DIR/nvim/init.vim" && PATERN='"##' && [ ! -z "$2" ] && INPUT="$2"
[ "$1" = "help" ] && line="$CHOISE"

sr1=$(grep "^$PATERN" "$filename" | sed "s/$PATERN\(.*\):\(.*\)/\1 - \2/g" | grep -iF "$INPUT")
sr2=$(echo "$sr1" | sed "s/.*\s-\s//g")

[ -z "$grp" ] && line="$sr1"
[ "$grp" = "ssh" ] && line="$sr2" && echo "$line" | xclip -selection clipboard

echo "$line" | less
