#!/usr/bin/env bash
 
 #####  #    # #    #  ####  License: GNU GPLv3
 #    # ##   # #    # #      Year: 2023
 #      # #  # #    #  ####  
 #  ### #  # # #    #      # https://github.com/gnusd
 #    # #   ## #    # #    # http://gnusd.xyz 
 #####  #    #  ####   ####
 
# FILENAME: copyCli

cat $1 | wl-copy
