#!/usr/bin/env bash

  ####  #    # #    #  ####  License: GNU GPLv3
  #    # ##   # #    # #      Year: 2020
  #      # #  # #    #  ####
  #  ### #  # # #    #      # https://github.com/gnusd
  #    # #   ## #    # #    # http://gnusd.xyz
  ####  #    #  ####   ####

# FILENAME: cuesheet

echo "Name of cue sheet file"
read file
echo "Artists name"
read artist
echo "Title of album"
read title
echo "Relese year"
read year
echo "Genre"
read genre

if [ ".*.cue$" != "$file" ]
then
		file="$file".cue
fi

(echo "REM GENRE $genre"
echo "REM DATE $year"
echo "PERFORMER $artist"
echo "TITLE $title"
echo "FILE  WAVE") >> "$file"


# TRACK 01 AUDIO
# TITLE
# PERFORMER
# INDEX 01

