#!/usr/bin/env bash

  ####  #    # #    #  ####  License: GNU GPLv3
  #    # ##   # #    # #      Year: 2020
  #      # #  # #    #  ####
  #  ### #  # # #    #      # https://github.com/gnusd
  #    # #   ## #    # #    # http://gnusd.xyz
  ####  #    #  ####   ####

# FILENAME: cuesheet

case

		echo "Artists name" < read "artist"
		echo "Title of album" < read "title"
		echo "Relese year" < read "year"
		echo "Genre" < read "genre"



		REM GENRE
		REM DATE
		PERFORMER
		TITLE
		FILE  WAVE


		TRACK 01 AUDIO
		TITLE
		PERFORMER
		INDEX 01

