#!/usr/bin/env bash
 
  ####  #    # #    #  ####  License: GNU GPLv3
 #    # ##   # #    # #      Year: 2020
 #      # #  # #    #  ####  
 #  ### #  # # #    #      # https://github.com/gnusd
 #    # #   ## #    # #    # http://gnusd.xyz 
  ####  #    #  ####   ####
 
# FILENAME: gitrepo
repo="$1"
dir="/home/media/git"

if [ "$repo" != .*".git"*. ]
then
	reponame="$repo.git"
else
	reponame="$repo"
fi

mkdir "$dir/$reponame" && cd "$dir/$reponame"  && git init --bare
cd "$dir" && sudo chown git:git "$reponame"
