#!/usr/bin/env bash
 
 #####  #    # #    #  ####  License: GNU GPLv3
 #    # ##   # #    # #      Year: 2023
 #      # #  # #    #  ####  
 #  ### #  # # #    #      # https://github.com/gnusd
 #    # #   ## #    # #    # http://gnusd.xyz 
 #####  #    #  ####   ####
 
# FILENAME: moviecheck

BASE_DIR="$HOME/mnt/downloads/play-dl/files"
RSS_FILE="rss.xml"

read_rss () {
    while read -r line
	do
        
    done < "${BASE_DIR}/${RSS_FILE}"
}