#!/usr/bin/env bash

  ####  #    # #    #  ####  License: GNU GPLv3
 #    # ##   # #    # #      Year: 2020
 #      # #  # #    #  ####
 #  ### #  # # #    #      # https://github.com/gnusd
 #    # #   ## #    # #    # http://gnusd.xyz
  ####  #    #  ####   ####

# FILENAME newpost

AUTHOR="gnus"

BASE_DIR="$HOME/hugo/gnusd.xyz/content/posts"
DS=$(date +'%Y-%m-%d')
TITLE="$*"
EXTENSION=".md"

NEW_POST_FILE="$DS" "$TITLE$EXTENSION"
NEW_POST=$(echo "$NEW_POST_FILE" | sed 's/\s/_/g;s/\//-/g')
[ -f "$BASE_DIR/$NEW_POST" ] && echo "File exists!" && exit

{
echo "---"
echo "title: \"$TITLE\""
echo "author: \"$AUTHOR\""
echo "date: \"$DS\""
echo "description: \"\""
echo "tags: []"
echo "draft: true"
echo "---"
} >> "$BASE_DIR/$NEW_POST"

nvim "$BASE_DIR/$NEW_POST"
