#!/usr/bin/env bash

AUTHOR="gnus"

BASE_DIR="$HOME/hugo/gnusd.xyz/content/posts"
DS=$(date +'%Y-%m-%d')
TITLE="$*"
EXTENSION=".md"

NEW_POST_FILE="$DS"_"$TITLE$EXTENSION"
NEW_POST=$(echo "$NEW_POST_FILE" | sed 's/\s/_/g;s/\//-/g')
[ -f "$BASE_DIR/$NEW_POST" ] && echo "File exists!" && exit

echo "---" >> "$BASE_DIR/$NEW_POST"
echo "title: \"$TITLE\"" >> "$BASE_DIR/$NEW_POST"
echo "author: \"$AUTHOR\"" >> "$BASE_DIR/$NEW_POST"
echo "date: \"$DS\"" >> "$BASE_DIR/$NEW_POST"
echo "description: \"\"" >> "$BASE_DIR/$NEW_POST"
echo "tags: []" >> "$BASE_DIR/$NEW_POST"
echo "draft: true" >> "$BASE_DIR/$NEW_POST"
echo "---" >> "$BASE_DIR/$NEW_POST"

nvim "$BASE_DIR/$NEW_POST"
