#!/usr/bin/env bash
 
  ####  #    # #    #  ####  License: GNU GPLv3
 #    # ##   # #    # #      Year: 2020
 #      # #  # #    #  ####  
 #  ### #  # # #    #      # https://github.com/gnusd
 #    # #   ## #    # #    # http://gnusd.xyz 
  ####  #    #  ####   ####
 
# FILENAME: pl-dl

youtube-dl --ignore-errors --format bestaudio --extract-audio --audio-format flac --audio-quality 0 --output "%(playlist_index)s - %(title)s.%(ext)s" --yes-playlis "$1"
