#!/usr/bin/env bash

  ####  #    # #    #  ####  License: GNU GPLv3
 #    # ##   # #    # #      Year: 2020
 #      # #  # #    #  ####
 #  ### #  # # #    #      # https://github.com/gnusd
 #    # #   ## #    # #    # http://gnusd.xyz
  ####  #    #  ####   ####

# FILENAME: pmv

INPUT="$1"
process=$(pgrep -x "$INPUT")

ask() {
		echo "Did you mean $prop? [y/N] "
		read -r response
}
pmv() {
		reptyr "$(pgrep -x "$pmove")" && exit
}

psp=$(ps -a | sed "/[A-Z]/d;s/^.*[0-9]\s\(.*\)/\1/g")

[ -z "$process" ] && search=$(tre-agrep -2 -iw "$INPUT" <<< "$psp")

search=$(echo "$search" | sed /[0-9]:/d)

[ -z "$search" ] && echo "$INPUT is not a running process." && exit

nprocesses=$(echo "$search" | sed "s/.*\s//g")

if [ -z "$nprocesses" ]
then
		prop="$check"
		ask
		if [ "$response" != "${response#[Yy]}" ]
		then
				pmove="$check"
				echo "$pmove"
		else
				exit
		fi
else
		for prop in $check
		do
				ask
				if [ "$response" != "${response#[Yy]}" ]
				then
						pmove="$prop"
						echo "$pmove"
				fi
		done
fi
