#!/bin/bash

cron=$1

cd $HOME/repositories/
path=$(pwd)
paths="$path/*"
n=0
u=0
dt=$(date '+%Y/%m/%d %H:%M:%S')
declare -a ignore=("dotfiles" "scripts")

function check_ignore {
  for e in "${ignore[@]}"
  do
    if [[ "$e" == "$1" ]]
    then
      return 1
    fi
  done
}

for dirs in $paths
do
		file_type=$(file $dirs)
		if [ "$file_type" == "$dirs: directory" ]
		then
				dir=$(echo $dirs | sed -e 's|'$path'/||g')
				if check_ignore $dir
				then
						let n++
						cd $dirs
						status=$(git pull)
						if [ "$status" != "Redan à jour." ]
						then
								let u++
								if [ $cron == "-e" ]
								then
										echo "$dt repos has been updated" > repo_update
										notify-send "$dir has been updated!"
								else
										echo  "$dir has been updated!"
								fi
						fi
				fi
		fi
done

cd $path
echo "[$dt] $n repositories have been checked, $u repositories updated.\n" >> repo_update.log
