#!/bin/bash

cd $HOME/repositories/
path=$(pwd)
paths="$path/*"
n=0
declare -a ignore=("dotfiles" "scripts")

function check_ignore {
  for e in "${ignore[@]}"
  do
    if [[ "$e" == "$1" ]]
    then
      return 1
    fi
  done
}

for dirs in $paths
do
		file_type=$(file $dirs)
		if [ "$file_type" == "$dirs: directory" ]
		then
				dir=$(echo $dirs | sed -e 's|'$path'/||g')
				if check_ignore $dir
				then
						let n++
						cd $dirs
						status=$(git pull)
						if [ "$status" != "Redan à jour." ]
						then
								notify-send "$dir has been updated!"
								echo  "$dir has been updated!"
						fi
				fi
		fi
done

echo "$n repositories have been checked."
