#!/usr/bin/env bash

  ####  #    # #    #  ####  License: GNU GPLv3
  #    # ##   # #    # #      Year: 2020
  #      # #  # #    #  ####
  #  ### #  # # #    #      # https://github.com/gnusd
  #    # #   ## #    # #    # http://gnusd.xyz
  ####  #    #  ####   ####

# FILENAME: rsyncTyrell
SEND="$1"
DESTINATION="$2"
rsync -rvz -e 'ssh -p 22' --progress "$SEND"  gnus@192.168.1.135:"$DESTINATION"
