#!/bin/bash

#Script to monitor the network and put changes to notification

#Check if lnet_scan exists
if [ ! -f /tmp/lnet_scan ]
then
		touch /tmp/lnet_scan
fi

#Copy previous lnet_scan file or empathy file to .back
mv /tmp/lnet_scan /tmp/lnet_scan.back

#get numeric list of online hosts
nmap -n -sn 192.168.1.* >> /tmp/lnet_scan
nmap -n -sn 192.168.2.* >> /tmp/lnet_scan

#Collect the difference, only the lines with ip-numbers
message=$(diff /tmp/lnet_scan.back /tmp/lnet_scan | grep 192 | sed -e 's| Nmap scan report for ||g')

#Create array of message
payload=(${message// / })

# Associative array for device names
declare -A names
names["192.168.1.1"]="WiredHub"
names["192.168.1.99"]="JF_Sebastian"
names["192.168.1.113"]="Deckard"
names["192.168.1.234"]="TyrellCorp"
names["192.168.2.1"]="WirelessHub"
names["192.168.2.82"]="Hogwarts"
names["192.168.2.121"]="Voight-Kampff"
names["192.168.2.130"]="Batty"
names["192.168.2.218"]="Gaff"
names["192.168.2.224"]="Potter"

for device in ${payload[@]}
do
		status_device=${device:0:1}

		u=${device:1}
		if [ -z ${names[$u]} ]
		then
				dev=$u
		else
				dev=${names[$u]}
		fi

		if [ "$status_device" == ">" ]
		then
				stat="uppkopplad"
		elif  [ "$status_device" == "<" ]
		then
				stat="nerkopplad"
		fi
		if [ "$u" != "192.168.1.72" ]
		then
				notify-send "$dev är $stat på lokalt nätverk." --icon=/home/gnus/nextcloud/bilder/icon/dev.png
		fi
done
