#!/usr/bin/env bash

  ####  #    # #    #  ####  License: GNU GPLv3
  #    # ##   # #    # #      Year: 2020
  #      # #  # #    #  ####
  #  ### #  # # #    #      # https://github.com/gnusd
  #    # #   ## #    # #    # http://gnusd.xyz
  ####  #    #  ####   ####

# FILENAME: spaudio

function split(){
		cuebreakpoints "$cuefile" | shnsplit -o flac "$audiofile"
		cuetag "$cuefile" split-track*.flac
}

for file in *
do
		ext="${file##*.}"
		if [[ "$ext" == "cue" ]]
				cuefile="$file"

		else if [[ "$audiofiles" == *"$ext"* ]]
				if [[ "$ext" == "flac" ]]
						audiofile="$file"
				else if [[ "$ext" == "ape" ]]
						no_spaces="${file// /_}"
						filename="${no_spaces%%.*}.flac"
						ffmpeg -i "$file" -c:a flac "$filename"
						audiofile="$filename"
						rm "$file"
				fi
				fi
		done

		split "$cue" "$audiofile"
		rm "$audiofile"
