#!/usr/bin/env bash
 
  ####  #    # #    #  ####  License: GNU GPLv3
 #    # ##   # #    # #      Year: 2020
 #      # #  # #    #  ####  
 #  ### #  # # #    #      # https://github.com/gnusd
 #    # #   ## #    # #    # http://gnusd.xyz 
  ####  #    #  ####   ####
 
# FILENAME: toflac

toflac () {
	file="${input// /_}"
	filename="${file%%.*}.flac"
	ffmpeg -i "$input" -c:a flac $filename && rm "$input"
}

for file in *
do
	ext="${file##*.}"
	case "$ext" in
		ape | wv | m4a)
			input="$file"
			toflac
			;;
		*)
	esac
done
