#!/usr/bin/env bash

ssh_user="ssh $USER@"
pane1="192.168.1.113"   # Deckard
pane2="192.168.1.234"   # tyrellCorp
pane3="192.168.1.99"    # JF Sebastian
pane4="207.154.212.191" # Stimagst
pane5="192.168.2.120"   # Voight-Kampff
pane6="94.237.93.110"   # off-world

command1=$("sudo apt update && sudo apt upgrade")
command2=$("sudo pkcon refresh -p && sudo pkcon update -p")
send="C-m"

tmux rename-session Update \; new-window -t Update split-window -h $ssh_user$pane1 send $command2 $send \; split-window -h $ssh_user$pane2  \; send $command1 $send \; split-window -h $ssh_user$pane3  \; send $command1 $send \; split-window -h $ssh_user$pane4  \; send $command1 $send \; split-window -h $ssh_user$pane5  \; send $command2 $send \;  split-window -h $ssh_user$pane6  \; send $command1 $send \; select-layout even-vertical \;