#!/bin/sh

address=$(xclip -o -selection clipboard)
result=$(echo "$address" | grep "http")

[ -z "$result" ] && exit
mpv --ontop --no-border --autofit=540x324 --geometry=99%:2% "$address" >> /dev/null &
exit
