#!/bin/sh
#
# author: gnus
# https://github.com/gnusd/

# input, current selected clipboard
address=$(xclip -o -selection clipboard)

# checks so it's a youtube channel address
result=$(echo "$address" | grep -P '(?=.*youtube)(?=.*channel)')
echo "$result"

# checks if $result is empthy, if so it insert blank line to clipboard and exit
[ -z "$result" ] &&  echo "" | xclip -selection clipboard && exit

# some regex to get the name of the channel
feed=$(echo "$address" | sed "s/.*\/channel\///g;s/\/.*//g")

# create rss link with channel name
rss="https://www.youtube.com/feeds/videos.xml?channel_id=$feed"

# echo to xclip
echo "$rss" | xclip -selection clipboard
